### PR TITLE
Fix/event backup complete

### LINKED ISSUE #295: Backup complete status event not logged
When backup is completed, the event is not sent to event server (e.g. Riemann), not logged into database. Backup report is generated based on the event of backup completion. If the event not found the backup is declared as not triggered even though status was completed and successful.
This happens as status polling code is moved to scheduler process instead of broker process. Currently in scheduler process there is no listener is subscribed to any event, even though the event is published. 
Happening in following build:
service fabrik: https://github.com/cloudfoundry-incubator/service-fabrik-broker/archive/2018.T05b.tar.gz

### PR DESCRIPTION
**Pull request by sauravmndl**
This fixes #295
Fix is to initialise all the event listener in service fabrik scheduler worker.

### CODE REVIEW

File: broker/JobScheduler.js [hunk 1]
```diff
@@ -74,6 +75,8 @@ class JobScheduler {
     process.on('message', (msg) => this.handleMessage(msg));
     logger.info(`Starting Service Fabrik Batch Job worker: ${cluster.worker.id} - ${process.pid}  @${new Date()}`);
     require('./lib/jobs');
+    logger.info('Initializing event listeners..');
```
Comment (jagadish-kb) [inline broker/JobScheduler.js]: Can you please remove this logger? or make it debug? in the long run we see too many unnecessary log statements in our app.
