### PR TITLE
Enhance backup report

### LINKED ISSUE #252: Enhancements in backup reporting
getInstanceBackupSummary:
  count of total no of triggered backups = # of entries in jobrundetails collection (scheduler was up and triggered backup/ job was run)
  Failure count => 
      1. Update query
      2. Count total failures and list in failed backups (guid: date, no-guid: date)
  No backup days
     1. InstanceCreateDay=> if no entry in jobrundetails on instancecreateday then it won't be no backupday
     2. InstanceDeleteDay => If only deleted entry present on jobrundetails on delete day then it won't be no backup day

### PR DESCRIPTION
**Pull request by amitmalav**
Closes #252 
Changed aggregate query to find
No backup days on instance create and delete days are handled gracefully
Backup trigger count changed to job run count

### CODE REVIEW

File: lib/reports/BackupReportManager.js [hunk 1]
```diff
@@ -4,85 +4,131 @@ const _ = require('lodash');
...
-        } else {
-          currentDay = new Date(endTime);
-        }
-        if (lastRunDetail && (endTime > lastRunDetail.createdAt)) {
-          _.assign(instanceRecord, {
-            instanceDeleteTime: lastRunDetail.createdAt
+        // Check if start time is less than instance create time
+        return Promise.all([
+            Promise.try(() => {
+              if (jobDetail) {
```
Comment (jagadish-kb) [inline lib/reports/BackupReportManager.js]: Method growing too big. Modularize sections within 45-85 into two seperate functions and name the function which highlights that you are getting the correctedStartDate/endDate for the report based on the create/delete times of instance.

File: lib/reports/BackupReportManager.js [hunk 2]
```diff
@@ -157,78 +203,75 @@ class BackupReportManager {
...
+        createdAt: {
+          '$gte': startTime,
+          '$lt': endTime
+        }
       },
-      createdAt: {
-        $first: '$createdAt'
+      projection: {
+        metric: 1,
+        'request.backup_guid': 1,
```
Comment (jagadish-kb) [inline lib/reports/BackupReportManager.js]: by having a projection on backup guid, will it filter out results which dont have backup guid in request? For ex, run the below query:
```
db.eventdetails.find({eventName : 'create_backup', metric: 1, 'response.status' : {'$eq': 500}}).pretty();
```
you will see many backups which are failed due to timeouts i guess which dont have backup guids. I guess these are the entries which might come in as trigerred count ? so may be if you tweak projection here you might get the counts properly from eventDetails itself? Can you tweak projection to the below and try?
```
 ...
  request: 1
  response: 1
...
}
```

File: lib/reports/BackupReportManager.js [hunk 3]
```diff
@@ -4,85 +4,131 @@ const _ = require('lodash');
...
+              consecutiveBackupFailureCount += (windowEndIndex - windowStartIndex + 1) >= maxAllowedNoBackupDaysInRow ? (windowEndIndex - windowStartIndex + 2 - maxAllowedNoBackupDaysInRow) : 0;
+              windowEndIndex++;
+              windowStartIndex = windowEndIndex;
+            }
+            const summary = {
+              noBackupDays: noBackupDays,
+              backupsTriggerred: triggeredBackupCount,
+              backupsSucceeded: backupSuccessCount,
+              backupFailed: (resultBackups.length - backupSuccessCount),
+              failedBackupGuids: resultBackups.slice(backupSuccessCount),
```
Comment (jagadish-kb) [inline lib/reports/BackupReportManager.js]: One comment not with regards to here, but can you also tweak the script `generate-backup-report` to add another column `fail_reason` along with `failed_backup_guids` something like
```
failed_backup_reason=$(echo "$backup_summary" |
                            jq '.failedBackupGuids[] | "\(.response) \(.createdAt)"' |
                            tr '\n' ' ' |
                            sed -e 's/,/;/g'
                          )
```
This is a minor fix, but it will certainly make trouble shooting almost unnecessary. I know the column would be really huge, but that anyways would be word wrapped & only interested folks would expand and look at it. What say? Atleast as an analyzer of backup report this field certainly makes the job much easier.

File: lib/reports/BackupReportManager.js [hunk 4]
```diff
@@ -4,85 +4,131 @@ const _ = require('lodash');
...
+              if (jobDetail) {
+                _.assign(instanceRecord, {
+                  instanceCreateTime: jobDetail.createdAt
+                });
+                if (startTime <= moment.utc(jobDetail.createdAt).startOf('day').toDate()) {
+                  currentDay = moment.utc(jobDetail.createdAt).startOf('day').toDate();
+                  //Check if entry present in jobrundetails for current day (start day)
+                  return getJobRunDetailCount(currentDay, moment.utc(currentDay).endOf('day').toDate())
+                    .then(count => {
+                      logger.info('got count ', count);
```
[the remark this answers is not in the document]
Comment (amitmalav) [reply lib/reports/BackupReportManager.js]: Yes, missed these logs. I'll update all the logger statements.

File: lib/reports/BackupReportManager.js [hunk 5]
```diff
@@ -4,85 +4,131 @@ const _ = require('lodash');
...
+              }
+              consecutiveBackupFailureCount += (windowEndIndex - windowStartIndex + 1) >= maxAllowedNoBackupDaysInRow ? (windowEndIndex - windowStartIndex + 2 - maxAllowedNoBackupDaysInRow) : 0;
+              windowEndIndex++;
+              windowStartIndex = windowEndIndex;
+            }
+            const summary = {
+              noBackupDays: noBackupDays,
+              backupsTriggerred: triggeredBackupCount,
+              backupsSucceeded: backupSuccessCount,
+              backupFailed: (resultBackups.length - backupSuccessCount),
```
[the remark this answers is not in the document]
Comment (amitmalav) [reply lib/reports/BackupReportManager.js]: resultBackups only have success and failures. triggeredBackupCount is the count of backup jobs that were run by scheduler. `triggeredBackupCount = backupSuccessCount + backupFailureCount`

File: lib/reports/BackupReportManager.js (hunk 3 above)
Comment (amitmalav) [reply lib/reports/BackupReportManager.js]: Yes, that was the idea.

File: lib/reports/BackupReportManager.js (hunk 2 above)
Comment (amitmalav) [reply lib/reports/BackupReportManager.js]: In case backup_guid is not present in some document then resulted list will have empty value for backup_guid key but this document will be part of result

File: lib/reports/BackupReportManager.js (hunk 3 above)
Comment (jagadish-kb) [reply lib/reports/BackupReportManager.js]: rename `failedBackupGuids` to `failedBackups`

File: lib/reports/BackupReportManager.js (hunk 1 above)
Comment (amitmalav) [reply lib/reports/BackupReportManager.js]: Done!

File: lib/reports/BackupReportManager.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (amitmalav) [reply lib/reports/BackupReportManager.js]: Done!

File: lib/reports/BackupReportManager.js [hunk 6]
```diff
@@ -4,85 +4,131 @@ const _ = require('lodash');
...
+                if (startTime <= moment.utc(jobDetail.createdAt).startOf('day').toDate()) {
+                  currentDay = moment.utc(jobDetail.createdAt).startOf('day').toDate();
+                  //Check if entry present in jobrundetails for current day (start day)
+                  return getJobRunDetailCount(currentDay, moment.utc(currentDay).endOf('day').toDate())
+                    .then(count => {
+                      logger.info('got count ', count);
+                      if (!count) {
+                        logger.info('No backup scheduled on instance create day ', currentDay);
+                        currentDay = moment.utc(currentDay).add(1, 'days').toDate();
+                        logger.info('current day: ', currentDay);
```
[the remark this answers is not in the document]
Comment (amitmalav) [reply lib/reports/BackupReportManager.js]: Done!

File: lib/reports/BackupReportManager.js [hunk 7]
```diff
@@ -4,85 +4,131 @@ const _ = require('lodash');
...
+              if (lastRunDetail && (endTime > lastRunDetail.createdAt)) {
+                _.assign(instanceRecord, {
+                  instanceDeleteTime: lastRunDetail.createdAt
+                });
+                endTime = lastRunDetail.createdAt;
+                //check if more than one entries present in jobrundetails on delete day
+                return getJobRunDetailCount(moment.utc(endTime).startOf('day').toDate(), endTime)
+                  .then(count => {
+                    if (!count) {
+                      logger.info('instance deleted before backup was taken on ', endTime);
```
[the remark this answers is not in the document]
Comment (amitmalav) [reply lib/reports/BackupReportManager.js]: Done!

File: test/reports.BackupReportManager.spec.js [hunk 8]
```diff
@@ -153,22 +163,54 @@ describe('BackupReportManager', function () {
...
+          expect(count).to.eql(triggeredBackupCount);
+          expect(repoSpy.count.callCount).to.equal(1);
         });
     });
   });
 
   describe('#getBackupResult', function () {
     it('should return list of successful and failed backups successfully', function () {
+      const criteria = {
+        searchBy: {
```
[the remark this answers is not in the document]
Comment (amitmalav) [reply test/reports.BackupReportManager.spec.js]: criteria format is different for different queries.
